### ISSUE TITLE
Sign-up page (phone verification)

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#160]
AC:
- [x] Use new designs for the phone verification page in the sign-up workflow.
- [x] Add dropdown to select country code.

*Desktop designs:* https://xd.adobe.com/view/8c5cfc43-3c65-4ab9-8704-5a74f6bb4a5d-d90f/
*Mobile designs:* https://xd.adobe.com/view/9828d767-f54c-4527-a8eb-8a64b28c8100-cd7b/

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] an error message should appear and the user should not go to the code form after pressing the "WEITER" button if the phone field is not filled

![sign up tel.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/54681c84-635e-4aeb-a200-662ec9db43a1)

- [ ] image is disapeared (mob /web)

-ACTUAL 
 ![image.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c6c5b4cf-bf8e-4206-9053-f6ad4c530655)
- EXECTED
![image1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/edb4ebd8-3241-44f4-b63c-ba73161e7632)

- [ ] the text "Hier anmelden" is not made as a link
![chrome_YZz3AdzB3n.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b142cb88-07e4-411a-bc6b-5be75cf6f582)

**Comment by Natali-Oliinyk-qa** [comment]
-  [ ] user has the opportunity to go to the form for entering his data during registration by entering a fictitious phone number and code
![chrome_fiMNa5iiGW.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b95f0a30-7d6d-4fbb-b589-355848ef3141)
