### ISSUE TITLE
Transaction page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#162]
AC:
- [ ] Use new designs for the transaction page.

**Comment by Natali-Oliinyk-qa** [comment]
- there is no currency sign in the PREIs column

![Screenshot_11.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/4f100d2b-35e3-4a1f-a68c-4f0a554bf0a0)

EXPECTED
![expected.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3827d49b-72f8-42d4-a609-c6c5d6d0040b)
_________________________________________________________________________________
- [x] MOBILE the text of the two columns is joined
![mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3f165a3c-3f28-4d32-af57-e2e46d5af480)
_________________________________________________________________________________
- [x] The data in the columns have shifted (on all pages (1-5))
![mob2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/9270967d-e1c7-472f-8c74-6b0423840cec)
