### ISSUE TITLE
Affiliate page

### ISSUE THREAD

**Issue by VovkodavOleksandr** [Aurumcopia-DE/aurumcopia-zenhub#168]
Affiliate program page:

Desktop designs - https://xd.adobe.com/view/5ba30250-d439-4e5c-9e8c-f11f5a51be39-0ef0/	
Mobile designs - https://xd.adobe.com/view/53835e0e-8000-446c-99a9-855e11a32b91-06d0/

**Comment by VovkodavOleksandr** [comment]
- [ ]  Descktop - https://xd.adobe.com/view/5ba30250-d439-4e5c-9e8c-f11f5a51be39-0ef0/	
- [ ]  Mobile - https://xd.adobe.com/view/53835e0e-8000-446c-99a9-855e11a32b91-06d0/

**Comment by Natali-Oliinyk-qa** [comment]
### **WEB**
- [x] the color and placement of the text does not match the layout

- ACTUAL 

![text1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/61b23a03-a6d4-42cd-a32d-6ab9e7a578a2)
- EXPECTED
![text2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/99586359-66f1-4d42-9a0c-8d696c14a617)
__________________________________________________________________________________________
- [x] placement of the text do not match the layout
- [x] placement of the text do not match the layout

- ACTUAL  ![text2.1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/cd7abc48-1372-4fc2-9bfc-342cfa09425c)

- EXPECTED
![text2.2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e4920a0e-66c1-41ea-a5c3-20d8c30759fe)

________________________________________________________________________________________
- [x] uncentered text on the form

- ACTUAL 
![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/67fa6def-4e5f-4571-856e-5ee7d0adc00e)
_______________________________________________________________________________________________
-  [x] the message about the copied link is displayed in English![copied.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e82b9f85-0a66-4806-bee2-c92a96e33a31)
______________________________________________________________________________________________________
-  [x] the generated link opens the old version of the registration page
![chrome_uDXPr0wmpq.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/11269b90-86b2-49ee-936d-4e03b8cd580c)
__________________________________________________________________________________________
- [x] refreshing the page takes the user to the login page
![рефреш.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/75239267-0c52-4cb8-a79c-6ffd5a096569)
___________________________________________________________________________________________
### _MOBILE_
-  [x] the color and font of the text does not match the layout
- ACTUAL 
![mobAC1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b3ce4646-b2d4-49fe-8151-a28185819860)
- EXPECTED![mobAC.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/9f0831d7-9937-4882-a31e-4f0921b94050)
________________________________________________________________________
- [x] the text moved to the next line
- [x] there is no space between the button and the textarea
- ACTUAL
![Screenshot_6.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/bc42f58e-4bbb-4825-be80-db8f8d69442c)
- EXPECTED
![Screenshot_10.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e52f8e74-b35b-403f-bc1c-8939c623c03a)
_________________________________________________________________

- [x] the form does not match the layout (3 headers on the layout)
- ACTUAL
![Screenshot_7.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/052b3ab6-139b-4011-be2a-a016e8a60e3c)  

- EXPECTED
![Screenshot_9.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c7cfc178-6ec6-4521-8efd-e53d2c0da1f2)

**Comment by yuliiakachmaryk** [comment]
@Natali-Oliinyk-qa  - refreshing the page takes the user to the login page
This is correct behavior. After updating the page, a request to update the token passes and from the login you automatically go back as an authorized user.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] MOBILE  the word " kopiert"  shift around the screen in different extensions for different devices
![chrome_ci5Cx3alsB.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/19a24487-38ab-4f0f-9dd9-17b9f612335d)

______________________________________________________________________________________________
 ![mobbug1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/153d8b50-5c23-458f-9a54-c97c14a878d1)
___________________________________________________________________
- [x] the values ​​in the TOTAL column have shifted
 ![mobbug2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ec03a70c-2464-4bd0-9c88-bb3761c087a9)
