### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by aleksandra-mileant** [Aurumcopia-DE/aurumcopia-zenhub#170]
AC:
- [x] Add desktop version
- [x] Add mobile version

**Comment by Natali-Oliinyk-qa** [comment]
- [x] different texts on the layout for mob and web version

![Screenshot_2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/2012ca91-3c75-4757-bd21-f9bf1ba0d941)

![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ed688fe3-44d2-44fc-ae8d-6ab53149befa)
_____________________________________________________________________________________________________

-   [x] this text is missing on the main page (not on the layout)

- ### **EXPECTED RES**
![expectedR.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/4ad902f8-7610-424c-aff9-0a7da7ca8fcd)
![expectedR2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/41a5e74c-3263-43d1-af97-9780386cfa3a)


- ### **ACTUAL RES**


WEB should be
![actualWEB.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/25a8a4c7-ba6b-41d1-a416-0d3877974590)
MOB should be
![actualmob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/5be329c8-f612-42a2-9e3a-7917c4d66036)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] ### **disconnect (there are 2 words) MOB and WEB**

![Screenshot_3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/6ed1aa4f-a1b0-4baf-89b8-7c09c3df00d2)
_________________________________________________________________________
 - [x] need to center the sentence MOBILE
- 1
![отцентровать.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e656c7cc-ded7-4980-b396-c1818ef7b2e4)
- 2
 ![отцентровать3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/2fa4098f-c139-499e-a6dc-c6a28fb72beb)


- 3 
![отцентровать1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d34630b9-0a4f-4582-a214-ff233c141a50)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] the link cannot be opened in a new tab![chrome_WKv0MSko3H.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ae474d8a-6792-403e-9bc2-b256c45df4da)

**Comment by Natali-Oliinyk-qa** [comment]
-  [x] **Different texts in web and mobile versions**
![Screenshot_4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b142aba1-5b2e-491a-8dc5-ffa75766b565)
![Screenshot_5.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3583c946-c6cf-427e-9576-2c1bef72c16a)

**Comment by Natali-Oliinyk-qa** [comment]
![chrome_Ce61ufAO62.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/0e572dc7-69b0-49cb-937f-bf043eb73d45)

**Comment by Natali-Oliinyk-qa** [comment]
-  [x] the words of the third line need to be pulled up to the second (it's all one big sentence,
 and visually as torn)  MOBILE
![mob centered.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/4abbd586-4830-493d-b2d5-21052a04b358)

**Comment by Natali-Oliinyk-qa** [comment]
- [X] **Firefox 107.0.1 (64-біт)  (in this browser the picture is very blurry)**
![плыветКарт.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/f511d21f-d178-4ac8-935e-0ac157d2ebf0)![плыветКарт1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d1d82257-9b92-4058-8a0a-ad3125aa1cd2)
