### ISSUE TITLE
SideBar

### ISSUE THREAD

**Issue by bcmp4p1** [Aurumcopia-DE/aurumcopia-zenhub#171]
- Use new design for sidebar.

![image.png](https://images.zenhubusercontent.com/6270ce45b18ff5e9f59b2c12/6c9cfbfa-c30f-4d3c-9c27-7334d98afa69)

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] sidebar item should be purple when the user selects this item (Windows)
 
- ### **ACTUAL RES**
![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/a9c765cc-74cb-4513-bd44-6b3bb62f138f)

-  ### **EXPECTED RES**
![Screenshot_2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/6801d847-2393-41df-b5c5-0ee6aeada8a2)
