### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by bcmp4p1** [Aurumcopia-DE/aurumcopia-zenhub#172]
- [x] Add new design for footer

**Comment by Natali-Oliinyk-qa** [comment]
-  [x] **when clicking on these links, the user goes to the main page**
- Rückkauf
- Affiliate Programm
- So erreichst du uns
________________________________________________________________________________
- [ ] **links do not open in a new tab**

-  [ ] **maybe need to enlarge the icons and reduce the distance between them**
![Screenshot_3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/ef1a7b23-20f0-4f9d-8250-01036f29f59e)
![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/7ca14ecb-ebe7-46f6-86c4-dd79670caa3e)

**Comment by Natali-Oliinyk-qa** [comment]
- [ ]  user cannot open the link in a new tab in the footer

![chrome_0mlxE0CiEN.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/faf9bd16-59d7-4a0f-aa9e-12f828d44c29)
__________________________________________________________________________________
