### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#173]
AC:
- [x] Use new designs for the desktop **Dashboard** page.
- [x] Use new designs for the mobile **Dashboard** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] extra sign  " : "
![Screenshot_4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/882609cf-801c-4a7f-8d5e-955709d960d7)
_________________________________________________________________________
- [x] the location of the text, color and font of the letters does not match the layout(MOB)

- ACTUAL RES
![мobAR.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/587cc1c1-7ff5-4b3b-be46-301c919b1bf7)

- EXPECTED RES
![мob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/95a0b071-80f1-4722-a24d-fdd71f9a26dd)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] move the text and button according to the layout
       and the name of the country merges into one word -UnitedArabEmirates

- ACTUAL
![сenterred.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/62f9a1c6-17ef-4c9b-a899-7f384127a742)
![button.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e9b6689c-2885-48c2-86e9-15828e210e35)


- EXPECTED
![expected.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/8cb02dd6-5abf-49d4-8ef6-bfebf589582b)

_____________________________________________________
- [x] very light color of the letters

- ACTUAL
 (does not match the layout)![light letters actual.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/760a53bb-312b-4006-945c-c8685b4ac101)
- EXPECTED 
![light letters expected.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/f383bfd2-515a-40af-89b2-12dea8102674)

_______________________________________________________________________________

- [x] with such expansion, the text goes beyond the form
![mobbb.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/6a5a254b-6bf5-48fa-af6c-918f6ef4bcf7)

______________________________________________________
- [ ] 
there should be one more line on the form as on the layout
![moobb.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/62cd2bf9-918e-422a-b8e9-f7933bc94bc5)
