### ISSUE TITLE
Rechnungen page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#175]
AC:
- [ ] Use new designs for the desktop **Rechnungen** page.
- [ ] Use new designs for the mobile **Rechnungen** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] the text color is too light and these texts should be different colors  -the upper text should be darker (WEB and MOBILE)

- ### **ACTUAL RES**

![Screenshot_4.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/6d759b3a-00ad-4f79-83a2-8c3005e56415)
- ### **EXPECTED RES**
![layout.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b22225c6-044d-412d-9fb5-dca461056904)
