### ISSUE TITLE
Identität page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#176]
AC:
- [ ] Use new designs for the desktop **Identität** page.
- [ ] Use new designs for the mobile **Identität** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] you need to translate the button
![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e242c40a-db91-45d3-af0d-209fdc620e51)
___________________________________________________________________________
-  [ ] the information entered by the user about himself is not stored
![data.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/47b8a516-1f0f-4ecf-89f6-e909421335f4)
____________________________________________________________________
- [x] all fields must be translated into German
![Screenshot_2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/03ba3f1e-2029-478f-b18c-21639b15e84b)
____________________________________________________________________________
- [ ] strange floating bug that doesn't reproduce every time
![chrome_HHQm2v7cow.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/85616be1-688e-4f4f-9cfb-d313cd0183e5)
_______________________________________________________________
- [x] unsigned field names

- ACTUAL
![actual.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/50fe505d-06dd-411f-b698-3740689faf0a)

- EXPECTED
![excepted.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/8988fc3e-9b0d-4650-bf7a-ca6f9b2a3d56)
_______________________________________________

- [x] change field names to a darker color MOBILE

![Screenshot_3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/f53b65ad-11c7-4b5e-9e76-f60103038c32)


______________________________________________________________________
- [x] it is necessary to center the fields according to the layout

- ACTUAL
![centred.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/74761bab-ebc6-4f70-bc39-7e7dbe739d4c)
- EXPECTED
![excepted1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/366b3489-0bc0-4cc1-8515-32ba226dd4a3)
______________________________________________________________________________
- [x] field is missing (MOB and WEB)
![Screenshot_5.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/562def42-e63c-44ee-904f-67d0277d9204)

**Comment by bcmp4p1** [comment]
we dont have this option
![image.png](https://images.zenhubusercontent.com/6270ce45b18ff5e9f59b2c12/0360c800-2946-470c-a361-c954d4632193)
