### ISSUE TITLE
Sign-up workflow

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#177]
AC:
- [x] Use new designs for the desktop **Sign-up** workflow.
- [x] Use new designs for the mobile  **Sign-up** workflow.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] very light color of the letters
![chrome_9C2JNsvmeY.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b94720e5-ebab-449e-a31d-2fa384815b66)

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] maybe it is necessary to set some kind of validation on the max number of characters for the password?

_______________________________________________________________________________
- [ ] if you press the enter button, all the fields will be highlighted - "fill in the required fields"
And when the user starts to fill in these fields later, the user cannot see what all the fields are called
I suggest - the signature of the field should appear as soon as the user places the cursor on this field
Now the signature appears when the user enters 2 or more characters in the field
![chrome_74YL6kNLGA.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/59d0f747-a90b-4787-9c64-3303037c69d6)
____________________________________________________________________________________
- [ ] the text in these fields will be truncated (if something can be done about it)
![Screenshot_3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/90080c9e-1155-4f2c-9376-c34f58e254af)

**Comment by aleksandra-mileant** [comment]
1 . maybe it is necessary to set some kind of validation on the max number of characters for the password?
@Natali-Oliinyk-qa I don't think it's necessary. The main thing is to make it clear to the user that at least one character must be present.
2. I suggest - the signature of the field should appear as soon as the user places the cursor on this field
I think it would be better to indicate in the error itself not just "This field is required", but "Field 'Name' is required".
