### ISSUE TITLE
LAGERUNG Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#179]
AC:
- [x] Use new designs for the desktop **LAGERUNG** page.
- [x] Use new designs for the mobile **LAGERUNG** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] **cropped background around elements MOB**
### 
### **ACTUAL RES**
![mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/47a621f8-7c2b-4831-8d9d-3f75c74f8e3a)

### **EXPECTED RES**
![layout.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c98230a5-984c-49c4-91a0-194be12f8571)
