### ISSUE TITLE
ÜBER UNS Page

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#180]
AC:
- [ ] Use new designs for the desktop **ÜBER UNS** page.
- [ ] Use new designs for the mobile **ÜBER UNS** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x]  translate this sentence into German
- [x] align sentences as on the layout
- [ ]  when clicking on Twitter redirects to the main page

- ### **ACTUAL MOBILE**
![actual mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/687a773a-92e1-4094-ae23-f722913a8daa)

- ### **ACTUAL WEB**
![actual web.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/fded16e6-0494-4d13-8c7b-f6e72e9f25b3)

__________________________________________________________________________________________
- ### **EXPECTED RES MOB**
![mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/9fca8aee-d7c8-43a4-a15c-535ef9f4d751)

- ### **EXPECTED RES  WEB*
![web.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/a0fa51e1-f569-4fb6-93b8-63b105ef6fa1)

**Comment by bcmp4p1** [comment]
we dont have twitter link, we will add it later
