### ISSUE TITLE
Contact us Page FRONTEND

### ISSUE THREAD

**Issue by aleksandra-mileant** [Aurumcopia-DE/aurumcopia-zenhub#186]
AC:
- [x] Use new designs for the desktop **Contact us Page** page.
- [x] Use new designs for the mobile **Contact us Page** page.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] **message about incorrect phone number is not displayed**
- ### **AND as a user, it is not clear to me where the prompt is in the field, and where the entered text is perhaps the text that the user enters needs to be made darker**
(for example, in the "message" field there is a text-tip "Your Message" , this text has the same color as the text in the fields above, which I filled in)
![chrome_oPz3GKv87O.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/87e30187-e2bd-4c91-8b9e-e8652ec20f78)
