### ISSUE TITLE
Order by query

### ISSUE THREAD

**Issue by maksymmelnychuk** [Aurumcopia-DE/aurumcopia-zenhub#194]
- Add order by in query

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] was not sorted correctly by date
![chrome_n8d5lXSCmr.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/472d2d24-6542-4a52-9b48-4ba3a8d67eb5)

**Comment by Natali-Oliinyk-qa** [comment]
![bug.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/85801a7f-0206-435d-ae6c-a5259a6f1a68)
