### ISSUE TITLE
Meine Edelmetalle payout

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#196]
AC:
- [x] Fix payout price calculation.

**Comment by Natali-Oliinyk-qa** [comment]
-   ### **55.047010921682464*0.17=9.357991857**
![1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/d7b01b79-ed96-4336-b090-d781cd60bf4d)

____________________________________________________-
- ### 55090.60231884058*1.73=95306.7420115942
![2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b5bd3353-5fb1-45fc-b1ef-7fcdc84479d1)
_______________________________________________________________
- ### **1712.4993151672434*5.56=9521.49619232**
![3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/0ab44b5d-ea09-4bef-a653-066d615b2aee)
