### ISSUE TITLE
Design fixes

### ISSUE THREAD

**Issue by KostiaLevchenko** [Aurumcopia-DE/aurumcopia-zenhub#200]
AC:
- [x] Fix header on pages:
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/about-us
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/agb
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/imprint
- [x] Add redirect to sign-up page. 
page: https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/how-can-i-order
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/2712f017-18ad-4672-b3c0-663fbd15847b)
- [x] Add redirect to sign-up page
page: https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/storage
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/689c6e2f-daa2-4f31-a7fe-d4010925e5a6)
- [x] Add promo video (from the home page). 
page: https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/why-aurumcopia
![image.png](https://images.zenhubusercontent.com/602d05b97403e46872b5c017/c54468b2-3b5a-4333-9982-98c9165c15cb)

**Comment by Natali-Oliinyk-qa** [comment]
- [x] picture overlaps the text
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/storage
![11111111111111111.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/e3b75f5d-2429-4695-a865-b297a157f4f6)
____________________________________________________________
- [x] On the mockup and, accordingly, on the web and mob versions - text from the template
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/why-aurumcopia

![Screenshot_1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/abfc6532-4d18-4a5d-9a4a-4d9e04381071)
_________________________________________________
- [X] In the slider, the image and text are superimposed on each other
https://aurumcopia-client-y7n76hdv6a-ez.a.run.app/why-aurumcopia
![Screenshot_3.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/71518847-902d-443b-897e-39364db6df06)
