### ISSUE TITLE
Add admin check

### ISSUE THREAD

**Issue by maksymmelnychuk** [Aurumcopia-DE/aurumcopia-zenhub#204]
- Allow to sign-in or to do request only when user have role admin

**Comment by KostiaLevchenko** [comment]
@maksymmelnychuk can u provide 2 accounts for test: one with admin role and second - regular user
@Natali-Oliinyk-qa ping Max for accounts
admin panel link: https://aurumcopia-admin-panel-y7n76hdv6a-ez.a.run.app/
