### ISSUE TITLE
PREISGESTALTUNG

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [Aurumcopia-DE/aurumcopia-zenhub#220]
- [x] 1. PREISGESTALTUNG Page
 https://xd.adobe.com/view/efe96367-cc5e-4155-b3e8-63849885c87b-baba/

**Comment by Natali-Oliinyk-qa** [comment]
- [ ] make it darker as in the mockup![Screenshot_2.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/f027e0a0-7731-4079-a2d9-41780d0af37f)
![Screenshot_3.png]
(https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/5ace1d31-a983-45d5-9133-e2a943ed98f5)

________________________________________________
-[ ] the page does not open in the mob version
-[ ]  the page is missing in the footer

![chrome_brM2BHHjkJ.gif](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/2aabe016-1748-4b8c-a04e-dddf42d37724)

**Comment by maksymmelnychuk** [comment]
In the desktop mockup they are not darker, so what should I do?
![Screenshot 2022-12-09 at 13.31.02.png](https://images.zenhubusercontent.com/62a84cbc4396e600db1c657f/33a86756-dc2e-4e18-a33f-20013396f1cb)

**Comment by maksymmelnychuk** [comment]
I dont see this page "Preisübersicht" on the footer layout

![Screenshot 2022-12-09 at 13.36.49.png](https://images.zenhubusercontent.com/62a84cbc4396e600db1c657f/59b7decb-0f25-4689-b050-bdf735326bcc)
