### ISSUE TITLE
Meine Edelmetalle

### ISSUE THREAD

**Issue by Natali-Oliinyk-qa** [Aurumcopia-DE/aurumcopia-zenhub#230]
- [x] 1. where to change the text?
- [ ] 2. chart graph should show the price since someone buy gold 
- [x] 3. Payout button shouldnt be shown on error transactions
- [x] 4. remove the background color (textcolor with dot is enough) 
- [x] 5. change name: fixed -> Fest and flexible -> Flexibel

![1.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/37853de9-abdc-4cb7-a19b-31d2abaff859)

_____________________________________________________________________

________________________________________
- ### MOBILE**
- [x] - profile logo to the right
- [x]  - "Auszahlen" Button same distance up and down 
 ![mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b0ea1a33-fd91-4370-820d-669bcd65dcab)

**Comment by yuliiakachmaryk** [comment]
@Natali-Oliinyk-qa 
Kostia said not to do the second point.

**Comment by Natali-Oliinyk-qa** [comment]
- [x] the check box is not visible
![checkbox.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/08973bcf-9950-40a2-9e48-310bf7e033d8)

____________________________________________________
- [x] make according to the mockup

- [x] 
![withmockup.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/3a7fe93c-f802-4765-8c72-d2c4e9794ccb)
- [X]
![mob.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/b94a7ea3-c405-44fe-b28a-c8cb6865acac)
______________________________________________________
- [ ] IPhone 12 (real device)
![photo_2022-12-05_15-58-54.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/76d98178-c178-4226-8a26-3d628af2e790)2

**Comment by Natali-Oliinyk-qa** [comment]
- [x] 1. move the form with the graph to the right (so that it is centered, and it is better to stretch it to the right
2. dividing lines - different lengths of these lines
![photo_2022-12-07_16-37-29.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/c24769f2-aeec-471a-9c29-d1cd425baae4)

- [x]  the frame of the whole form is not centered
![photo_2022-12-07_16-40-54.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/56c40a44-45de-4a7a-b9d7-0950b8b74f4f)

________________________________________________________
- [x] button
![photo_2022-12-07_16-32-25.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/92bca21f-1389-4f9c-b5b3-213a15e92fb2)
_____________________________________________________
- [x]
![photo_2022-12-07_16-50-40.jpg](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/39ffcb4c-22f4-4632-9263-d976a1207f39) ]

**Comment by Natali-Oliinyk-qa** [comment]
- [x] didn't fix in mobile version
![unnamed.png](https://images.zenhubusercontent.com/6358f94433cd996ea0e90753/4d41707a-8bba-47d4-b5a9-f32963d64783)
